"""empty message

Revision ID: 0922e7cbc782
Revises: 
Create Date: 2022-08-18 00:42:43.800269

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import jheep



# revision identifiers, used by Alembic.
revision = '0922e7cbc782'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filestore',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('file',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', jheep.models.types.TIMESTAMPAware(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', jheep.models.types.TIMESTAMPAware(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('filestore_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['filestore_id'], ['filestore.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filestore_id', 'path')
    )
    op.create_index(op.f('ix_file_created_at'), 'file', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_updated_at'), 'file', ['updated_at'], unique=False)
    op.create_table('dataset',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data_schema', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mlmodel',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mlmodel')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_file_updated_at'), table_name='file')
    op.drop_index(op.f('ix_file_created_at'), table_name='file')
    op.drop_table('file')
    op.drop_table('filestore')
    # ### end Alembic commands ###