ARG DOCKER_REGISTRY="ghcr.io/jhee-group"

# base image
FROM ${DOCKER_REGISTRY}/jheep-base:latest

# entrypoint
COPY .settings/supervisord_server.conf /etc/supervisord.conf
CMD ["supervisord", "-c", "/etc/supervisord.conf"]
