"""empty message

Revision ID: fed1b5c4768b
Revises:
Create Date: 2022-06-15 17:11:21.181390

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from cns.models.generics import GUID, TIMESTAMPAware


# revision identifiers, used by Alembic.
revision = 'fed1b5c4768b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', TIMESTAMPAware(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', TIMESTAMPAware(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'artist')
    )
    op.create_index(op.f('ix_song_created_at'), 'song', ['created_at'], unique=False)
    op.create_index(op.f('ix_song_updated_at'), 'song', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_updated_at'), table_name='song')
    op.drop_index(op.f('ix_song_created_at'), table_name='song')
    op.drop_table('song')
    # ### end Alembic commands ###
